CREATE TABLE IF NOT EXISTS POMODORO_SETTINGS
(
    ID INTEGER PRIMARY KEY CHECK (ID = 1),
    WORK_DURATION INTEGER DEFAULT 25,
    SHORT_BREAK INTEGER DEFAULT 5,
    LONG_BREAK INTEGER DEFAULT 15,
    SESSIONS_UNTIL_LONG_BREAK INTEGER DEFAULT 4
);



INSERT OR IGNORE INTO POMODORO_SETTINGS (ID, WORK_DURATION, SHORT_BREAK, LONG_BREAK, SESSIONS_UNTIL_LONG_BREAK)
VALUES (1, 25, 5, 15, 4);